const ANKETA_CREATE='anketa_create';
const TRANSPORT_CREATE='transport_create';
const CONTRACT_CREATE='CONTRACT_CREATE'
const CONTRACT_ADD='CONTRACT_ADD'
export {ANKETA_CREATE, TRANSPORT_CREATE, CONTRACT_CREATE,CONTRACT_ADD}