const ANKETA_CREATE='anketa_create';
const TRANSPORT_CREATE='transport_create';
const CONTRACT_CREATE='CONTRACT_CREATE'
const CONTRACT_ADD='CONTRACT_ADD'
const OPLATA_CREATE='OPLATA_CREATE'
const OPLATA_ADD='OPLATA_ADD'
const POLIS_ADD='POLIS_ADD'
const POLIS_CREATE='POLIS_CREATE' 
const TRANSH_CREATE='TRANSH_CREATE' 
const OPLATA_DEL='OPLATA_DEL'; 
export {
		ANKETA_CREATE, 
		TRANSPORT_CREATE, 
		CONTRACT_CREATE,
		CONTRACT_ADD, 
		OPLATA_CREATE, 
		OPLATA_ADD, 
		POLIS_ADD, 
		POLIS_CREATE,
		TRANSH_CREATE,
		OPLATA_DEL
	}